language: node_js
node_js:
  - "8"
before_install:
  - 'nvm install-latest-npm'
env:
  matrix:
  - REACT=16.4
sudo: false
script:
  - npm run lint
  - npm run test
after_success:
  - npm run coverage
